name: AI Migrate cli

on:
  workflow_dispatch:
    inputs:
      VERSION:
        type: string
        description: Which VERSION?
        required: true
        default: ""

jobs:
  ai-cli:
    runs-on: ubuntu-latest
    env:
      ENV_FILE_PATH: ./.github/variables/stack_vars.env
      PROJECT_APPKEY: dynamodb
      VERSION:  ${{ github.event.inputs.VERSION}}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Checkout Project Source Code 🛒
        uses: actions/checkout@v4


      - name: 🛠️ Create .npmrc File
        run: |
          chmod 775 -R ./scripts && ./scripts/create-npmrc-file.sh
        ##########################################
      - name: Setup Node.js
      ##########################################
        uses: actions/setup-node@v3
        with:
          node-version: '20'


      - name: Create Environment
        uses: ./.github/actions/set-env-vars
        with:
          varFilePath: ${{ env.ENV_FILE_PATH }}


      - name: ✅ build
        run: |
          chmod 775 -R ./scripts/
          ./scripts/project-script.sh